language: go

go:
  - "1.x"
  - "tip"

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

jobs:
  include:
    - stage: coverage
      go: "1.x"
      before_install:
        - go get -v -u github.com/mattn/goveralls
      script:
        - $GOPATH/bin/goveralls -service=travis-ci -race -covermode=atomic ./...
