language: go
sudo: false
go:
  - "1.x"

addons:
  sonarcloud:
    organization: "jakebailey-github"
    token: $SONAR_TOKEN

before_install:
  - go get github.com/mattn/goveralls
  - curl -L https://git.io/vp6lP | BINDIR=${GOPATH=$HOME/go}/bin bash

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - $GOPATH/bin/gometalinter --disable=gosec ./... > gometalinter-report.out || true
  - go test -json ./... > report.json
  - go test -coverprofile=coverage.out ./...
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
